name: PR Checks
on:
    pull_request_target:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
    cancel-in-progress: true

permissions:
    id-token: write # This is required for requesting the JWT

jobs:
  set-workflow-environment:
    runs-on: ubuntu-latest
    outputs:
      workflow_env: ${{ steps.set-env.outputs.result }}
    steps:
      - name: Check Permissions & Set Workflow Environment
        uses: actions/github-script@v7
        id: set-env
        with:
          result-encoding: string
          debug: true
          script: | 
            const result = await github.rest.repos.checkCollaborator({
              owner: context.repo.owner,
              repo: context.repo.repo,
              username: "${{ github.event.pull_request.user.login }}",
            });
            return result.status == 204 ? "collab-env" : "pr-approval-env"
  codestyle-doc-tests:
    runs-on: ubuntu-latest
    needs: [set-workflow-environment]
    environment: ${{  needs.set-workflow-environment.outputs.workflow_env }}
    steps: 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Codestyle & Doc Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-codestyle-doc-tests
          source-version-override: 'pr/${{ github.event.pull_request.number }}'
  unit-tests:
    runs-on: ubuntu-latest
    needs: [set-workflow-environment]
    environment: ${{  needs.set-workflow-environment.outputs.workflow_env }}
    strategy:
        fail-fast: false
        matrix:
          python-version: ["py38","py39","py310","py311"]
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Unit Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-unit-tests
          source-version-override: 'pr/${{ github.event.pull_request.number }}'
          env-vars-for-codebuild: |
            PY_VERSION
        env:
          PY_VERSION: ${{ matrix.python-version }}
