name: PR Checks
on:
    pull_request_target:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.head_ref }}
    cancel-in-progress: true

permissions:
    id-token: write # This is required for requesting the JWT

jobs:
  check-access:
    runs-on: ubuntu-latest
    steps:
      - name: Check Access
        if: ${{ github.triggering_actor.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'MEMBER' }}
        run: |
          echo '${{ toJSON(github) }}'
          echo "Event not triggered by a collaborator."
          exit 1
  codestyle-doc-tests:
    runs-on: ubuntu-latest
    needs: [check-access]
    if: needs.check-access.result == 'success'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Codestyle & Doc Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-codestyle-doc-tests
          source-version-override: 'pr/${{ github.event.pull_request.number }}'
  unit-tests:
    runs-on: ubuntu-latest
    needs: [check-access]
    strategy:
        fail-fast: false
        matrix:
          python-version: ["py38","py39","py310","py311"]
    if: needs.check-access.result == 'success'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Unit Tests
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: sagemaker-python-sdk-ci-unit-tests
          source-version-override: 'pr/${{ github.event.pull_request.number }}'
          env-vars-for-codebuild: |
            PY_VERSION
        env:
          PY_VERSION: ${{ matrix.python-version }}
