name: Run Slow Tests

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: 'Pull Request Number'
        required: true
      commitSha:
        description: 'Commit SHA'
        required: true

concurrency:
    group: ${{ github.workflow }}-${{ github.event.inputs.prNumber }}
    cancel-in-progress: true

permissions:
    id-token: write # This is required for requesting the JWT

jobs:
    slow-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
              role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
              aws-region: us-west-2
              role-duration-seconds: 10800
        - name: Run Slow Tests
          uses: aws-actions/aws-codebuild-run-build@v1
          with:
              project-name: ${{ github.event.repository.name }}-ci-slow-tests
              source-version-override: 'refs/pull/${{ github.event.inputs.prNumber}}/head^{${{ github.event.inputs.commitSha }}}'
      
