name: Run Slow Tests

on:
  workflow_call:
    inputs:
      prNumber:
        required: true
        type: number
      commitSha:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.prNumber }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  local-mode-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE_ARN }}
          aws-region: us-west-2
          role-duration-seconds: 10800
      - name: Run Test
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: ${{ github.repository.name }}-ci-slow-tests
          source-version-override: 'refs/pull/${{ inputs.prNumber }}/head^{${{ inputs.commitSha }}}'